name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Create .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "IRON_SESSION_PASSWORD=${{ secrets.IRON_SESSION_PASSWORD }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
